version: "3.4"

name: mealie

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest #

    container_name: mealie
    restart: always
    ports:
      - "9925:9000" #

    deploy:
      resources:
        limits:
          memory: 1000M #

    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: http://localhost

  static-builder:
    build: ./static-builder
    environment:
      API_KEY_FILE: /run/secrets/mealie_api_key
      LIST_ID: e27baaa6-9057-43c3-a64d-16b8218fc4e1
    volumes:
      - ../static-site:/site
    secrets:
      - mealie_api_key

secrets:
  mealie_api_key:
    file: ./mealie-api-key.txt

volumes:
  mealie-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/raid2023/Src/src/devops/mealie-static/data
